# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:11.2.0

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
          - npm run build
    - step:
        name: Deploy
        deployment: production
        script:
          - pipe: atlassian/sftp-deploy:0.3.1
            variables:
              USER: 'ferrydeploy'
              SERVER: 'ssh.lianza.org'
              REMOTE_PATH: 'larkspurferry.cf'
              LOCAL_PATH: 'build/'
              # SSH_KEY: '<string>' # Optional.
              # EXTRA_ARGS: '<string>' # Optional.
              # DEBUG: '<boolean>' # Optional.


